version: '3.5' # We use version 3.5 syntax
services: # Here we define our service(s)
  angular-service: # The name of the service
    container_name: admin-portal  # Container name
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4200:4200' # Port mapping
