version: '3.5' # We use version 3.5 syntax
services: # Here we define our service(s)
  admin-portal: # The name of the service
    hostname: localhost
    container_name: admin-portal
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - node_modules:/usr/src/app/node_modules
    ports:
      - 80:80
    networks:
      - web-network

volumes:
  node_modules:
  ssl_data_conf:
  ssl_data_www:

networks:
  web-network:
    driver: bridge
