spring:
  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB

  jpa:
    database: default
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # multiTenancy: SCHEMA 
        # tenant_identifier_resolver: "com.softel.mpesa.multitenancy.TenantIdentifierResolver"
        # multi_tenant_connection_provider: "com.softel.mpesa.multitenancy.AnotherMultiTenantConnectionProvider"
sms:
  africas-talking-api-key: 8e45a01d6c49cf849d223aa5f695125a8f165be144741fa1fd302a795cd6b25e
  softel-sms-api-key: 68c1f195-4d7d-4476-8813-82760a11189d
mpesa:
  consumer-key: 76mdKGBCJaeZsAruFG0GQWR6zPOQW4vN
  consumer-secret: xlAkAuoHcwaLog0F
  base-url: https://api.safaricom.co.ke
  short-code: 4045353
  passkey: 3f601f4c6ae8e28954a88e62986ae1d6b536c91773b0ebbd3b098686b35509c7
  token:
    duration:
      seconds: 3600
  client-credentials:
    oauth-url: /oauth/v1/generate?grant_type=client_credentials
  mpesa-express:
    request-url: https://api.safaricom.co.ke/mpesa/stkpush/v1/processrequest
    callback-url: https://softwareelegance.net/api/vuka/express/callback
    query-url: https://api.safaricom.co.ke/mpesa/stkpushquery/v1/query
  b2c:
    initiator-name: testapi
    password: Safaricom584!#
    shortcode: 4045353
    security-credential: Safaricom584!#
    msisdn: 4045353
    request-url: /mpesa/b2c/v1/paymentrequest
    result-url: /mpesa-gateway/mpesa-b2c/result-callback
    queue-timeout-url: /mpesa-gateway/mpesa-b2c/queue-timeout-callback
  c2b:
    simulate-c2b-url: wip
    validation-url: wip
    confirmation-url: wip
    
softel:
  api:
    base-url: https://softwareelegance.net/api/



