spring:
  jackson:
    serialization:
      fail-on-empty-beans: false #Solves lazy fetching issue on serialization
  application:
    name: mpesa-gateway
  profiles:
    active: dev

# eureka:
#    client:
#       serviceUrl:
#           defaultZone: http://localhost:8761/eureka
#       preferIpAddress: true
#       registerWithEureka: true
#       fetchRegistry: true


management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: false
  endpoints:
    web:
      base-path: /actuator
      # By default, only 'health' and 'info' are accessible via web
      exposure:
        include: '*' 


logging:
  file: mpesa-gateway.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
  level:
    root: INFO
    org:
      springframework:
        web: INFO
      hibernate:
        SQL: ERROR
      type:
        decriptor:
          sql:
            BasicBinder: TRACE



