version: '3.9'

services:

  admin-portal:
    image: zeguru/vuka-admin-portal:rc9
    container_name: vuka_admin_portal
    restart: unless-stopped
    volumes:
      - node_modules:/usr/src/app/node_modules
    ports:
      - 80:80
    depends_on:
      - mpesa
      - adminer
    networks:
      - app-network

  mpesa:
    image: zeguru/vuka-mpesa-gateway:rc16
    container_name: vuka_mpesa_gateway
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - app-network
    env_file:
      - prod-env/mpesa.env

  redis:
    image: redis
    container_name: vuka_redis
    command: [ "redis-server", "--protected-mode", "no" ]
    hostname: redis
    expose: 
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis/redis-data:/var/lib/redis
      - $PWD/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: vuka_adminer
    restart: always
    # depends_on:
      # - db
    ports:
      - 8888:8080
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_HOST: db
      ADMINER_DEFAULT_DB_NAME: mpesa_gateway
    networks:
      - app-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: vuka_redis_commander
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
    networks:
      - app-network

volumes:
  node_modules:
  ssl_data_conf:
  ssl_data_www:

networks:
  app-network:
    driver: "bridge"