version: '3.9'

services:

  mpesa:
    build:
      context: ./mpesa-gateway/
      dockerfile: Dockerfile.min
    container_name: app_mpesa_vuka
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    networks:
      - app-network
    env_file:
      - mpesa-gateway/mpesa.env

  redis:
    image: redis
    container_name: app_redis_vuka
    command: [ "redis-server", "--protected-mode", "no" ]
    hostname: redis
    expose: 
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis/redis-data:/var/lib/redis
      - $PWD/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - app-network


  db:
    image: postgres:12
    container_name: app_db_vuka
    hostname: db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./postgres-configs/scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network
    env_file:
      - postgres-configs/pg.env

  # adminer:
  #     image: adminer
  #     restart: always
  #     depends_on:
  #     - db
  #     ports:
  #       - 8888:8080


networks:
  app-network:
    driver: "bridge"