version: '3.9'

services:

  admin-portal:
    image: zeguru/vuka-admin-portal:rc2
    container_name: vuka_admin_portal
    restart: unless-stopped
    volumes:
      - node_modules:/usr/src/app/node_modules
    ports:
      - 80:80
    depends_on:
      - mpesa
      - adminer
    networks:
      - app-network

  mpesa:
    image: zeguru/vuka-mpesa-gateway:rc6
    container_name: vuka_mpesa_gateway
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - app-network
    env_file:
      - prod-env/mpesa.env


  adminer:
      image: adminer
      container_name: vuka_adminer
      restart: always
      # depends_on:
        # - db
      ports:
        - 8888:8080
      environment:
        ADMINER_DEFAULT_DB_DRIVER: pgsql
        ADMINER_DEFAULT_DB_HOST: db
        ADMINER_DEFAULT_DB_NAME: mpesa_gateway
      networks:
        - app-network

volumes:
  node_modules:
  ssl_data_conf:
  ssl_data_www:


networks:
  app-network:
    driver: "bridge"