version: '3.9'

services:
  admin-portal:
    image: zeguru/vuka-admin-portal:rc6
    container_name: app_admin_portal_vuka
    restart: unless-stopped
    volumes:
      - node_modules:/usr/src/app/node_modules
    ports:
      - 80:80
    depends_on:
      - db
      - redis
      - mpesa
      - adminer
    networks:
      - app-network

  mpesa:
    image: zeguru/vuka-mpesa-gateway:rc16
    container_name: app_mpesa_vuka
    restart: unless-stopped
    ports:
      - "68080:8080"
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    networks:
      - app-network
    env_file:
      - uat-env/mpesa.env


  redis:
    image: redis
    container_name: app_redis_vuka
    command: [ "redis-server", "--protected-mode", "no" ]
    hostname: redis
    expose: 
      - "6379"
    ports:
      - "66379:6379"
    volumes:
      - $PWD/redis/redis-data:/var/lib/redis
      - $PWD/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - app-network


  db:
    image: postgres:12
    container_name: app_db_vuka
    hostname: db
    restart: unless-stopped
    ports:
      - "65432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./postgres-configs/scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network
    env_file:
      - uat-env/pg.env

  
  adminer:
      image: adminer
      container_name: app_adminer_vuka
      restart: always
      depends_on:
        - db
      ports:
        - 68888:8080
      environment:
        ADMINER_DEFAULT_DB_DRIVER: pgsql
        ADMINER_DEFAULT_DB_HOST: db
        ADMINER_DEFAULT_DB_NAME: mpesa_gateway
      networks:
        - app-network


  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: vuka_redis_commander
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 68081:8081
    networks:
      - app-network

  keycloak:
      image: quay.io/keycloak/keycloak:latest
      container_name: app_keycloak_vuka
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: db
        DB_DATABASE: mpesa_gateway
        DB_USER: dev_user
        DB_PASSWORD: caro_kann
        DB_SCHEMA: public
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 69009:8080
      depends_on:
        - db
      networks:
        - app-network

volumes:
  node_modules:
  ssl_data_conf:
  ssl_data_www:

networks:
  app-network:
    driver: "bridge"